merging with remote branch

diff --git a/.github/workflows/run-ci.yaml b/.github/workflows/run-ci.yaml
--- a/.github/workflows/run-ci.yaml
+++ b/.github/workflows/run-ci.yaml
@@ -39,33 +39,23 @@ jobs:
       - name: 🧪 Run tests with coverage
         run: |
           poetry run pytest --cov=src --cov-report=xml --cov-report=term-missing
-
-      - name: 📈 Save coverage report
-        uses: actions/upload-artifact@v4
-        with:
-          name: coverage-report
-          path: coverage_artifacts/coverage.xml
-
-      - name: 🏷️ Generate coverage badge
-        run: |
           poetry run coverage-badge -o coverage.svg -f
 
-      - name: 📥 Save artifacts locally
-        run: |
-          mkdir -p coverage_artifacts
-          mv coverage.xml coverage_artifacts/
-          mv coverage.svg coverage_artifacts/
-
-      - name: 📈 Commit and push coverage artifacts
+      - name: 📥 Save coverage badge and report
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
+          mkdir -p coverage_artifacts
+
+          mv coverage.xml coverage_artifacts/ || echo "coverage.xml not found"
+          mv coverage.svg coverage_artifacts/ || echo "coverage.svg not found"
+
           git config user.name "github-actions"
           git config user.email "github-actions@github.com"
+
           git add coverage_artifacts/
           git commit -m "Add coverage artifacts"
           git push
-
 
       - name: 🧹 Run flake8 as Linter
         run: |
